[package]
name = "chalkboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
strip = "symbols"
lto = "thin"

[dependencies]
bevy = {version = "0.13.2", features=["jpeg"]}
rand = "0.8.5"
